// <auto-generated />
namespace Inventory.DATA.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class June3850 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(June3850));
        
        string IMigrationMetadata.Id
        {
            get { return "202006031250064_June3850"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
