// <auto-generated />
namespace Inventory.DATA.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class may26 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(may26));
        
        string IMigrationMetadata.Id
        {
            get { return "202005261602491_may26"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
